author           = InnovAnon
depends          = default,3d_armor,ia_util,player_monoids,tidesandfloods
description      = Temperature
name             = ia_thermal
optional_depends =
title            = IA Thermal

